package com.example.app.presentation.chat.reactions

object Reactions {

    val emojiSet = listOf(
        // Popular
        Reaction("Popular", "+1", "1f44d"),
        Reaction("Popular", "tada", "1f389"),
        Reaction("Popular", "smile", "1f642"),
        Reaction("Popular", "heart", "2764"),
        Reaction("Popular", "working_on_it", "1f6e0"),
        Reaction("Popular", "octopus", "1f419"),

        // Smileys & Emotion
        Reaction("Smileys & Emotion", "grinning", "1f600"),
        Reaction("Smileys & Emotion", "smiley", "1f603"),
        Reaction("Smileys & Emotion", "big_smile", "1f604"),
        Reaction("Smileys & Emotion", "grinning_face_with_smiling_eyes", "1f601"),
        Reaction("Smileys & Emotion", "laughing", "1f606"),
        Reaction("Smileys & Emotion", "sweat_smile", "1f605"),
        Reaction("Smileys & Emotion", "rolling_on_the_floor_laughing", "1f923"),
        Reaction("Smileys & Emotion", "joy", "1f602"),
        Reaction("Smileys & Emotion", "smile", "1f642"),
        Reaction("Smileys & Emotion", "upside_down", "1f643"),
        Reaction("Smileys & Emotion", "wink", "1f609"),
        Reaction("Smileys & Emotion", "blush", "1f60a"),
        Reaction("Smileys & Emotion", "innocent", "1f607"),
        Reaction("Smileys & Emotion", "heart_eyes", "1f60d"),
        Reaction("Smileys & Emotion", "heart_kiss", "1f618"),
        Reaction("Smileys & Emotion", "kiss", "1f617"),
        Reaction("Smileys & Emotion", "smiling_face", "263a"),
        Reaction("Smileys & Emotion", "kiss_with_blush", "1f61a"),
        Reaction("Smileys & Emotion", "kiss_smiling_eyes", "1f619"),
        Reaction("Smileys & Emotion", "yum", "1f60b"),
        Reaction("Smileys & Emotion", "stuck_out_tongue", "1f61b"),
        Reaction("Smileys & Emotion", "stuck_out_tongue_wink", "1f61c"),
        Reaction("Smileys & Emotion", "stuck_out_tongue_closed_eyes", "1f61d"),
        Reaction("Smileys & Emotion", "money_face", "1f911"),
        Reaction("Smileys & Emotion", "hug", "1f917"),
        Reaction("Smileys & Emotion", "thinking", "1f914"),
        Reaction("Smileys & Emotion", "silence", "1f910"),
        Reaction("Smileys & Emotion", "neutral", "1f610"),
        Reaction("Smileys & Emotion", "expressionless", "1f611"),
        Reaction("Smileys & Emotion", "speechless", "1f636"),
        Reaction("Smileys & Emotion", "smirk", "1f60f"),
        Reaction("Smileys & Emotion", "unamused", "1f612"),
        Reaction("Smileys & Emotion", "rolling_eyes", "1f644"),
        Reaction("Smileys & Emotion", "grimacing", "1f62c"),
        Reaction("Smileys & Emotion", "lying", "1f925"),
        Reaction("Smileys & Emotion", "relieved", "1f60c"),
        Reaction("Smileys & Emotion", "pensive", "1f614"),
        Reaction("Smileys & Emotion", "sleepy", "1f62a"),
        Reaction("Smileys & Emotion", "drooling", "1f924"),
        Reaction("Smileys & Emotion", "sleeping", "1f634"),
        Reaction("Smileys & Emotion", "cant_talk", "1f637"),
        Reaction("Smileys & Emotion", "sick", "1f912"),
        Reaction("Smileys & Emotion", "hurt", "1f915"),
        Reaction("Smileys & Emotion", "nauseated", "1f922"),
        Reaction("Smileys & Emotion", "sneezing", "1f927"),
        Reaction("Smileys & Emotion", "dizzy", "1f635"),
        Reaction("Smileys & Emotion", "cowboy", "1f920"),
        Reaction("Smileys & Emotion", "sunglasses", "1f60e"),
        Reaction("Smileys & Emotion", "nerd", "1f913"),
        Reaction("Smileys & Emotion", "oh_no", "1f615"),
        Reaction("Smileys & Emotion", "worried", "1f61f"),
        Reaction("Smileys & Emotion", "frown", "1f641"),
        Reaction("Smileys & Emotion", "sad", "2639"),
        Reaction("Smileys & Emotion", "open_mouth", "1f62e"),
        Reaction("Smileys & Emotion", "hushed", "1f62f"),
        Reaction("Smileys & Emotion", "astonished", "1f632"),
        Reaction("Smileys & Emotion", "flushed", "1f633"),
        Reaction("Smileys & Emotion", "frowning", "1f626"),
        Reaction("Smileys & Emotion", "anguished", "1f627"),
        Reaction("Smileys & Emotion", "fear", "1f628"),
        Reaction("Smileys & Emotion", "cold_sweat", "1f630"),
        Reaction("Smileys & Emotion", "exhausted", "1f625"),
        Reaction("Smileys & Emotion", "cry", "1f622"),
        Reaction("Smileys & Emotion", "sob", "1f62d"),
        Reaction("Smileys & Emotion", "scream", "1f631"),
        Reaction("Smileys & Emotion", "confounded", "1f616"),
        Reaction("Smileys & Emotion", "persevere", "1f623"),
        Reaction("Smileys & Emotion", "disappointed", "1f61e"),
        Reaction("Smileys & Emotion", "sweat", "1f613"),
        Reaction("Smileys & Emotion", "weary", "1f629"),
        Reaction("Smileys & Emotion", "anguish", "1f62b"),
        Reaction("Smileys & Emotion", "triumph", "1f624"),
        Reaction("Smileys & Emotion", "rage", "1f621"),
        Reaction("Smileys & Emotion", "angry", "1f620"),
        Reaction("Smileys & Emotion", "smiling_devil", "1f608"),
        Reaction("Smileys & Emotion", "devil", "1f47f"),
        Reaction("Smileys & Emotion", "skull", "1f480"),
        Reaction("Smileys & Emotion", "skull_and_crossbones", "2620"),
        Reaction("Smileys & Emotion", "poop", "1f4a9"),
        Reaction("Smileys & Emotion", "clown", "1f921"),
        Reaction("Smileys & Emotion", "ogre", "1f479"),
        Reaction("Smileys & Emotion", "goblin", "1f47a"),
        Reaction("Smileys & Emotion", "ghost", "1f47b"),
        Reaction("Smileys & Emotion", "alien", "1f47d"),
        Reaction("Smileys & Emotion", "space_invader", "1f47e"),
        Reaction("Smileys & Emotion", "robot", "1f916"),
        Reaction("Smileys & Emotion", "smiley_cat", "1f63a"),
        Reaction("Smileys & Emotion", "smile_cat", "1f638"),
        Reaction("Smileys & Emotion", "joy_cat", "1f639"),
        Reaction("Smileys & Emotion", "heart_eyes_cat", "1f63b"),
        Reaction("Smileys & Emotion", "smirk_cat", "1f63c"),
        Reaction("Smileys & Emotion", "kissing_cat", "1f63d"),
        Reaction("Smileys & Emotion", "scream_cat", "1f640"),
        Reaction("Smileys & Emotion", "crying_cat", "1f63f"),
        Reaction("Smileys & Emotion", "angry_cat", "1f63e"),
        Reaction("Smileys & Emotion", "see_no_evil", "1f648"),
        Reaction("Smileys & Emotion", "hear_no_evil", "1f649"),
        Reaction("Smileys & Emotion", "speak_no_evil", "1f64a"),
        Reaction("Smileys & Emotion", "lipstick_kiss", "1f48b"),
        Reaction("Smileys & Emotion", "love_letter", "1f48c"),
        Reaction("Smileys & Emotion", "cupid", "1f498"),
        Reaction("Smileys & Emotion", "gift_heart", "1f49d"),
        Reaction("Smileys & Emotion", "sparkling_heart", "1f496"),
        Reaction("Smileys & Emotion", "heart_pulse", "1f497"),
        Reaction("Smileys & Emotion", "heartbeat", "1f493"),
        Reaction("Smileys & Emotion", "revolving_hearts", "1f49e"),
        Reaction("Smileys & Emotion", "two_hearts", "1f495"),
        Reaction("Smileys & Emotion", "heart_box", "1f49f"),
        Reaction("Smileys & Emotion", "heart_exclamation", "2763"),
        Reaction("Smileys & Emotion", "broken_heart", "1f494"),
        Reaction("Smileys & Emotion", "heart", "2764"),
        Reaction("Smileys & Emotion", "yellow_heart", "1f49b"),
        Reaction("Smileys & Emotion", "green_heart", "1f49a"),
        Reaction("Smileys & Emotion", "blue_heart", "1f499"),
        Reaction("Smileys & Emotion", "purple_heart", "1f49c"),
        Reaction("Smileys & Emotion", "black_heart", "1f5a4"),
        Reaction("Smileys & Emotion", "100", "1f4af"),
        Reaction("Smileys & Emotion", "anger", "1f4a2"),
        Reaction("Smileys & Emotion", "boom", "1f4a5"),
        Reaction("Smileys & Emotion", "seeing_stars", "1f4ab"),
        Reaction("Smileys & Emotion", "sweat_drops", "1f4a6"),
        Reaction("Smileys & Emotion", "dash", "1f4a8"),
        Reaction("Smileys & Emotion", "hole", "1f573"),
        Reaction("Smileys & Emotion", "bomb", "1f4a3"),
        Reaction("Smileys & Emotion", "umm", "1f4ac"),
        Reaction("Smileys & Emotion", "speech_bubble", "1f5e8"),
        Reaction("Smileys & Emotion", "anger_bubble", "1f5ef"),
        Reaction("Smileys & Emotion", "thought", "1f4ad"),
        Reaction("Smileys & Emotion", "zzz", "1f4a4"),

// People & Body
        Reaction("People & Body", "wave", "1f44b"),
        Reaction("People & Body", "stop", "1f91a"),
        Reaction("People & Body", "high_five", "1f590"),
        Reaction("People & Body", "hand", "270b"),
        Reaction("People & Body", "spock", "1f596"),
        Reaction("People & Body", "ok", "1f44c"),
        Reaction("People & Body", "peace_sign", "270c"),
        Reaction("People & Body", "fingers_crossed", "1f91e"),
        Reaction("People & Body", "rock_on", "1f918"),
        Reaction("People & Body", "call_me", "1f919"),
        Reaction("People & Body", "point_left", "1f448"),
        Reaction("People & Body", "point_right", "1f449"),
        Reaction("People & Body", "point_up", "1f446"),
        Reaction("People & Body", "middle_finger", "1f595"),
        Reaction("People & Body", "point_down", "1f447"),
        Reaction("People & Body", "wait_one_second", "261d"),
        Reaction("People & Body", "+1", "1f44d"),
        Reaction("People & Body", "-1", "1f44e"),
        Reaction("People & Body", "fist", "270a"),
        Reaction("People & Body", "fist_bump", "1f44a"),
        Reaction("People & Body", "left_fist", "1f91b"),
        Reaction("People & Body", "right_fist", "1f91c"),
        Reaction("People & Body", "clap", "1f44f"),
        Reaction("People & Body", "raised_hands", "1f64c"),
        Reaction("People & Body", "open_hands", "1f450"),
        Reaction("People & Body", "handshake", "1f91d"),
        Reaction("People & Body", "pray", "1f64f"),
        Reaction("People & Body", "writing", "270d"),
        Reaction("People & Body", "nail_polish", "1f485"),
        Reaction("People & Body", "selfie", "1f933"),
        Reaction("People & Body", "muscle", "1f4aa"),
        Reaction("People & Body", "ear", "1f442"),
        Reaction("People & Body", "nose", "1f443"),
        Reaction("People & Body", "eyes", "1f440"),
        Reaction("People & Body", "eye", "1f441"),
        Reaction("People & Body", "tongue", "1f445"),
        Reaction("People & Body", "lips", "1f444"),
        Reaction("People & Body", "baby", "1f476"),
        Reaction("People & Body", "boy", "1f466"),
        Reaction("People & Body", "girl", "1f467"),
        Reaction("People & Body", "man", "1f468"),
        Reaction("People & Body", "woman", "1f469"),
        Reaction("People & Body", "older_man", "1f474"),
        Reaction("People & Body", "older_woman", "1f475"),
        Reaction("People & Body", "person_frowning", "1f64d"),
        Reaction("People & Body", "person_pouting", "1f64e"),
        Reaction("People & Body", "no_signal", "1f645"),
        Reaction("People & Body", "ok_signal", "1f646"),
        Reaction("People & Body", "information_desk_person", "1f481"),
        Reaction("People & Body", "raising_hand", "1f64b"),
        Reaction("People & Body", "bow", "1f647"),
        Reaction("People & Body", "face_palm", "1f926"),
        Reaction("People & Body", "shrug", "1f937"),
        Reaction("People & Body", "police", "1f46e"),
        Reaction("People & Body", "detective", "1f575"),
        Reaction("People & Body", "guard", "1f482"),
        Reaction("People & Body", "construction_worker", "1f477"),
        Reaction("People & Body", "prince", "1f934"),
        Reaction("People & Body", "princess", "1f478"),
        Reaction("People & Body", "turban", "1f473"),
        Reaction("People & Body", "gua_pi_mao", "1f472"),
        Reaction("People & Body", "bride", "1f470"),
        Reaction("People & Body", "pregnant", "1f930"),
        Reaction("People & Body", "angel", "1f47c"),
        Reaction("People & Body", "santa", "1f385"),
        Reaction("People & Body", "mother_christmas", "1f936"),
        Reaction("People & Body", "massage", "1f486"),
        Reaction("People & Body", "haircut", "1f487"),
        Reaction("People & Body", "walking", "1f6b6"),
        Reaction("People & Body", "running", "1f3c3"),
        Reaction("People & Body", "dancer", "1f483"),
        Reaction("People & Body", "dancing", "1f57a"),
        Reaction("People & Body", "levitating", "1f574"),
        Reaction("People & Body", "dancers", "1f46f"),
        Reaction("People & Body", "fencing", "1f93a"),
        Reaction("People & Body", "horse_racing", "1f3c7"),
        Reaction("People & Body", "skier", "26f7"),
        Reaction("People & Body", "snowboarder", "1f3c2"),
        Reaction("People & Body", "golf", "1f3cc"),
        Reaction("People & Body", "surf", "1f3c4"),
        Reaction("People & Body", "rowboat", "1f6a3"),
        Reaction("People & Body", "swim", "1f3ca"),
        Reaction("People & Body", "ball", "26f9"),
        Reaction("People & Body", "lift", "1f3cb"),
        Reaction("People & Body", "cyclist", "1f6b4"),
        Reaction("People & Body", "mountain_biker", "1f6b5"),
        Reaction("People & Body", "cartwheel", "1f938"),
        Reaction("People & Body", "wrestling", "1f93c"),
        Reaction("People & Body", "water_polo", "1f93d"),
        Reaction("People & Body", "handball", "1f93e"),
        Reaction("People & Body", "juggling", "1f939"),
        Reaction("People & Body", "bath", "1f6c0"),
        Reaction("People & Body", "in_bed", "1f6cc"),
        Reaction("People & Body", "two_women_holding_hands", "1f46d"),
        Reaction("People & Body", "man_and_woman_holding_hands", "1f46b"),
        Reaction("People & Body", "two_men_holding_hands", "1f46c"),
        Reaction("People & Body", "family", "1f46a"),
        Reaction("People & Body", "speaking_head", "1f5e3"),
        Reaction("People & Body", "silhouette", "1f464"),
        Reaction("People & Body", "silhouettes", "1f465"),
        Reaction("People & Body", "footprints", "1f463"),
        Reaction("People & Body", "tuxedo", "1f935"),

// Animals & Nature
        Reaction("Animals & Nature", "monkey_face", "1f435"),
        Reaction("Animals & Nature", "monkey", "1f412"),
        Reaction("Animals & Nature", "gorilla", "1f98d"),
        Reaction("Animals & Nature", "puppy", "1f436"),
        Reaction("Animals & Nature", "dog", "1f415"),
        Reaction("Animals & Nature", "poodle", "1f429"),
        Reaction("Animals & Nature", "wolf", "1f43a"),
        Reaction("Animals & Nature", "fox", "1f98a"),
        Reaction("Animals & Nature", "kitten", "1f431"),
        Reaction("Animals & Nature", "cat", "1f408"),
        Reaction("Animals & Nature", "lion", "1f981"),
        Reaction("Animals & Nature", "tiger_cub", "1f42f"),
        Reaction("Animals & Nature", "tiger", "1f405"),
        Reaction("Animals & Nature", "leopard", "1f406"),
        Reaction("Animals & Nature", "pony", "1f434"),
        Reaction("Animals & Nature", "horse", "1f40e"),
        Reaction("Animals & Nature", "unicorn", "1f984"),
        Reaction("Animals & Nature", "deer", "1f98c"),
        Reaction("Animals & Nature", "calf", "1f42e"),
        Reaction("Animals & Nature", "ox", "1f402"),
        Reaction("Animals & Nature", "water_buffalo", "1f403"),
        Reaction("Animals & Nature", "cow", "1f404"),
        Reaction("Animals & Nature", "piglet", "1f437"),
        Reaction("Animals & Nature", "pig", "1f416"),
        Reaction("Animals & Nature", "boar", "1f417"),
        Reaction("Animals & Nature", "pig_nose", "1f43d"),
        Reaction("Animals & Nature", "ram", "1f40f"),
        Reaction("Animals & Nature", "sheep", "1f411"),
        Reaction("Animals & Nature", "goat", "1f410"),
        Reaction("Animals & Nature", "arabian_camel", "1f42a"),
        Reaction("Animals & Nature", "camel", "1f42b"),
        Reaction("Animals & Nature", "elephant", "1f418"),
        Reaction("Animals & Nature", "rhinoceros", "1f98f"),
        Reaction("Animals & Nature", "dormouse", "1f42d"),
        Reaction("Animals & Nature", "mouse", "1f401"),
        Reaction("Animals & Nature", "rat", "1f400"),
        Reaction("Animals & Nature", "hamster", "1f439"),
        Reaction("Animals & Nature", "bunny", "1f430"),
        Reaction("Animals & Nature", "rabbit", "1f407"),
        Reaction("Animals & Nature", "chipmunk", "1f43f"),
        Reaction("Animals & Nature", "bat", "1f987"),
        Reaction("Animals & Nature", "bear", "1f43b"),
        Reaction("Animals & Nature", "koala", "1f428"),
        Reaction("Animals & Nature", "panda", "1f43c"),
        Reaction("Animals & Nature", "paw_prints", "1f43e"),
        Reaction("Animals & Nature", "turkey", "1f983"),
        Reaction("Animals & Nature", "chicken", "1f414"),
        Reaction("Animals & Nature", "rooster", "1f413"),
        Reaction("Animals & Nature", "hatching", "1f423"),
        Reaction("Animals & Nature", "chick", "1f424"),
        Reaction("Animals & Nature", "new_baby", "1f425"),
        Reaction("Animals & Nature", "bird", "1f426"),
        Reaction("Animals & Nature", "penguin", "1f427"),
        Reaction("Animals & Nature", "dove", "1f54a"),
        Reaction("Animals & Nature", "eagle", "1f985"),
        Reaction("Animals & Nature", "duck", "1f986"),
        Reaction("Animals & Nature", "owl", "1f989"),
        Reaction("Animals & Nature", "frog", "1f438"),
        Reaction("Animals & Nature", "crocodile", "1f40a"),
        Reaction("Animals & Nature", "turtle", "1f422"),
        Reaction("Animals & Nature", "lizard", "1f98e"),
        Reaction("Animals & Nature", "snake", "1f40d"),
        Reaction("Animals & Nature", "dragon_face", "1f432"),
        Reaction("Animals & Nature", "dragon", "1f409"),
        Reaction("Animals & Nature", "whale", "1f433"),
        Reaction("Animals & Nature", "humpback_whale", "1f40b"),
        Reaction("Animals & Nature", "dolphin", "1f42c"),
        Reaction("Animals & Nature", "fish", "1f41f"),
        Reaction("Animals & Nature", "tropical_fish", "1f420"),
        Reaction("Animals & Nature", "blowfish", "1f421"),
        Reaction("Animals & Nature", "shark", "1f988"),
        Reaction("Animals & Nature", "octopus", "1f419"),
        Reaction("Animals & Nature", "shell", "1f41a"),
        Reaction("Animals & Nature", "snail", "1f40c"),
        Reaction("Animals & Nature", "butterfly", "1f98b"),
        Reaction("Animals & Nature", "bug", "1f41b"),
        Reaction("Animals & Nature", "ant", "1f41c"),
        Reaction("Animals & Nature", "bee", "1f41d"),
        Reaction("Animals & Nature", "spider", "1f577"),
        Reaction("Animals & Nature", "web", "1f578"),
        Reaction("Animals & Nature", "scorpion", "1f982"),
        Reaction("Animals & Nature", "bouquet", "1f490"),
        Reaction("Animals & Nature", "cherry_blossom", "1f338"),
        Reaction("Animals & Nature", "white_flower", "1f4ae"),
        Reaction("Animals & Nature", "rosette", "1f3f5"),
        Reaction("Animals & Nature", "rose", "1f339"),
        Reaction("Animals & Nature", "wilted_flower", "1f940"),
        Reaction("Animals & Nature", "hibiscus", "1f33a"),
        Reaction("Animals & Nature", "sunflower", "1f33b"),
        Reaction("Animals & Nature", "blossom", "1f33c"),
        Reaction("Animals & Nature", "tulip", "1f337"),
        Reaction("Animals & Nature", "seedling", "1f331"),
        Reaction("Animals & Nature", "evergreen_tree", "1f332"),
        Reaction("Animals & Nature", "tree", "1f333"),
        Reaction("Animals & Nature", "palm_tree", "1f334"),
        Reaction("Animals & Nature", "cactus", "1f335"),
        Reaction("Animals & Nature", "harvest", "1f33e"),
        Reaction("Animals & Nature", "herb", "1f33f"),
        Reaction("Animals & Nature", "shamrock", "2618"),
        Reaction("Animals & Nature", "lucky", "1f340"),
        Reaction("Animals & Nature", "maple_leaf", "1f341"),
        Reaction("Animals & Nature", "fallen_leaf", "1f342"),
        Reaction("Animals & Nature", "leaves", "1f343"),
        Reaction("Animals & Nature", "beetle", "1f41e"),

// Food & Drink
        Reaction("Food & Drink", "grapes", "1f347"),
        Reaction("Food & Drink", "melon", "1f348"),
        Reaction("Food & Drink", "watermelon", "1f349"),
        Reaction("Food & Drink", "orange", "1f34a"),
        Reaction("Food & Drink", "lemon", "1f34b"),
        Reaction("Food & Drink", "banana", "1f34c"),
        Reaction("Food & Drink", "pineapple", "1f34d"),
        Reaction("Food & Drink", "apple", "1f34e"),
        Reaction("Food & Drink", "green_apple", "1f34f"),
        Reaction("Food & Drink", "pear", "1f350"),
        Reaction("Food & Drink", "peach", "1f351"),
        Reaction("Food & Drink", "cherries", "1f352"),
        Reaction("Food & Drink", "strawberry", "1f353"),
        Reaction("Food & Drink", "kiwi", "1f95d"),
        Reaction("Food & Drink", "tomato", "1f345"),
        Reaction("Food & Drink", "avocado", "1f951"),
        Reaction("Food & Drink", "eggplant", "1f346"),
        Reaction("Food & Drink", "potato", "1f954"),
        Reaction("Food & Drink", "carrot", "1f955"),
        Reaction("Food & Drink", "corn", "1f33d"),
        Reaction("Food & Drink", "hot_pepper", "1f336"),
        Reaction("Food & Drink", "cucumber", "1f952"),
        Reaction("Food & Drink", "mushroom", "1f344"),
        Reaction("Food & Drink", "peanuts", "1f95c"),
        Reaction("Food & Drink", "chestnut", "1f330"),
        Reaction("Food & Drink", "bread", "1f35e"),
        Reaction("Food & Drink", "croissant", "1f950"),
        Reaction("Food & Drink", "baguette", "1f956"),
        Reaction("Food & Drink", "pancakes", "1f95e"),
        Reaction("Food & Drink", "cheese", "1f9c0"),
        Reaction("Food & Drink", "meat", "1f356"),
        Reaction("Food & Drink", "drumstick", "1f357"),
        Reaction("Food & Drink", "bacon", "1f953"),
        Reaction("Food & Drink", "hamburger", "1f354"),
        Reaction("Food & Drink", "fries", "1f35f"),
        Reaction("Food & Drink", "pizza", "1f355"),
        Reaction("Food & Drink", "hotdog", "1f32d"),
        Reaction("Food & Drink", "taco", "1f32e"),
        Reaction("Food & Drink", "burrito", "1f32f"),
        Reaction("Food & Drink", "doner_kebab", "1f959"),
        Reaction("Food & Drink", "egg", "1f95a"),
        Reaction("Food & Drink", "cooking", "1f373"),
        Reaction("Food & Drink", "paella", "1f958"),
        Reaction("Food & Drink", "food", "1f372"),
        Reaction("Food & Drink", "salad", "1f957"),
        Reaction("Food & Drink", "popcorn", "1f37f"),
        Reaction("Food & Drink", "bento", "1f371"),
        Reaction("Food & Drink", "senbei", "1f358"),
        Reaction("Food & Drink", "onigiri", "1f359"),
        Reaction("Food & Drink", "rice", "1f35a"),
        Reaction("Food & Drink", "curry", "1f35b"),
        Reaction("Food & Drink", "ramen", "1f35c"),
        Reaction("Food & Drink", "spaghetti", "1f35d"),
        Reaction("Food & Drink", "yam", "1f360"),
        Reaction("Food & Drink", "oden", "1f362"),
        Reaction("Food & Drink", "sushi", "1f363"),
        Reaction("Food & Drink", "tempura", "1f364"),
        Reaction("Food & Drink", "naruto", "1f365"),
        Reaction("Food & Drink", "dango", "1f361"),
        Reaction("Food & Drink", "crab", "1f980"),
        Reaction("Food & Drink", "shrimp", "1f990"),
        Reaction("Food & Drink", "squid", "1f991"),
        Reaction("Food & Drink", "soft_serve", "1f366"),
        Reaction("Food & Drink", "shaved_ice", "1f367"),
        Reaction("Food & Drink", "ice_cream", "1f368"),
        Reaction("Food & Drink", "donut", "1f369"),
        Reaction("Food & Drink", "cookie", "1f36a"),
        Reaction("Food & Drink", "birthday", "1f382"),
        Reaction("Food & Drink", "cake", "1f370"),
        Reaction("Food & Drink", "chocolate", "1f36b"),
        Reaction("Food & Drink", "candy", "1f36c"),
        Reaction("Food & Drink", "lollipop", "1f36d"),
        Reaction("Food & Drink", "custard", "1f36e"),
        Reaction("Food & Drink", "honey", "1f36f"),
        Reaction("Food & Drink", "baby_bottle", "1f37c"),
        Reaction("Food & Drink", "milk", "1f95b"),
        Reaction("Food & Drink", "coffee", "2615"),
        Reaction("Food & Drink", "tea", "1f375"),
        Reaction("Food & Drink", "sake", "1f376"),
        Reaction("Food & Drink", "champagne", "1f37e"),
        Reaction("Food & Drink", "wine", "1f377"),
        Reaction("Food & Drink", "cocktail", "1f378"),
        Reaction("Food & Drink", "tropical_drink", "1f379"),
        Reaction("Food & Drink", "beer", "1f37a"),
        Reaction("Food & Drink", "beers", "1f37b"),
        Reaction("Food & Drink", "clink", "1f942"),
        Reaction("Food & Drink", "small_glass", "1f943"),
        Reaction("Food & Drink", "hungry", "1f37d"),
        Reaction("Food & Drink", "fork_and_knife", "1f374"),
        Reaction("Food & Drink", "spoon", "1f944"),
        Reaction("Food & Drink", "knife", "1f52a"),
        Reaction("Food & Drink", "vase", "1f3fa"),

// Activities
        Reaction("Activities", "jack-o-lantern", "1f383"),
        Reaction("Activities", "holiday_tree", "1f384"),
        Reaction("Activities", "fireworks", "1f386"),
        Reaction("Activities", "sparkler", "1f387"),
        Reaction("Activities", "sparkles", "2728"),
        Reaction("Activities", "balloon", "1f388"),
        Reaction("Activities", "tada", "1f389"),
        Reaction("Activities", "confetti", "1f38a"),
        Reaction("Activities", "wish_tree", "1f38b"),
        Reaction("Activities", "bamboo", "1f38d"),
        Reaction("Activities", "dolls", "1f38e"),
        Reaction("Activities", "carp_streamer", "1f38f"),
        Reaction("Activities", "wind_chime", "1f390"),
        Reaction("Activities", "moon_ceremony", "1f391"),
        Reaction("Activities", "ribbon", "1f380"),
        Reaction("Activities", "gift", "1f381"),
        Reaction("Activities", "reminder_ribbon", "1f397"),
        Reaction("Activities", "ticket", "1f39f"),
        Reaction("Activities", "pass", "1f3ab"),
        Reaction("Activities", "military_medal", "1f396"),
        Reaction("Activities", "trophy", "1f3c6"),
        Reaction("Activities", "medal", "1f3c5"),
        Reaction("Activities", "first_place", "1f947"),
        Reaction("Activities", "second_place", "1f948"),
        Reaction("Activities", "third_place", "1f949"),
        Reaction("Activities", "football", "26bd"),
        Reaction("Activities", "baseball", "26be"),
        Reaction("Activities", "basketball", "1f3c0"),
        Reaction("Activities", "volleyball", "1f3d0"),
        Reaction("Activities", "american_football", "1f3c8"),
        Reaction("Activities", "rugby", "1f3c9"),
        Reaction("Activities", "tennis", "1f3be"),
        Reaction("Activities", "strike", "1f3b3"),
        Reaction("Activities", "cricket", "1f3cf"),
        Reaction("Activities", "field_hockey", "1f3d1"),
        Reaction("Activities", "ice_hockey", "1f3d2"),
        Reaction("Activities", "ping_pong", "1f3d3"),
        Reaction("Activities", "badminton", "1f3f8"),
        Reaction("Activities", "boxing_glove", "1f94a"),
        Reaction("Activities", "black_belt", "1f94b"),
        Reaction("Activities", "gooooooooal", "1f945"),
        Reaction("Activities", "hole_in_one", "26f3"),
        Reaction("Activities", "ice_skate", "26f8"),
        Reaction("Activities", "fishing", "1f3a3"),
        Reaction("Activities", "running_shirt", "1f3bd"),
        Reaction("Activities", "ski", "1f3bf"),
        Reaction("Activities", "direct_hit", "1f3af"),
        Reaction("Activities", "billiards", "1f3b1"),
        Reaction("Activities", "crystal_ball", "1f52e"),
        Reaction("Activities", "video_game", "1f3ae"),
        Reaction("Activities", "joystick", "1f579"),
        Reaction("Activities", "slot_machine", "1f3b0"),
        Reaction("Activities", "dice", "1f3b2"),
        Reaction("Activities", "spades", "2660"),
        Reaction("Activities", "hearts", "2665"),
        Reaction("Activities", "diamonds", "2666"),
        Reaction("Activities", "clubs", "2663"),
        Reaction("Activities", "joker", "1f0cf"),
        Reaction("Activities", "mahjong", "1f004"),
        Reaction("Activities", "playing_cards", "1f3b4"),
        Reaction("Activities", "performing_arts", "1f3ad"),
        Reaction("Activities", "picture", "1f5bc"),
        Reaction("Activities", "art", "1f3a8"),

// Travel & Places
        Reaction("Travel & Places", "earth_africa", "1f30d"),
        Reaction("Travel & Places", "earth_americas", "1f30e"),
        Reaction("Travel & Places", "earth_asia", "1f30f"),
        Reaction("Travel & Places", "www", "1f310"),
        Reaction("Travel & Places", "map", "1f5fa"),
        Reaction("Travel & Places", "japan", "1f5fe"),
        Reaction("Travel & Places", "snowy_mountain", "1f3d4"),
        Reaction("Travel & Places", "mountain", "26f0"),
        Reaction("Travel & Places", "volcano", "1f30b"),
        Reaction("Travel & Places", "mount_fuji", "1f5fb"),
        Reaction("Travel & Places", "campsite", "1f3d5"),
        Reaction("Travel & Places", "beach", "1f3d6"),
        Reaction("Travel & Places", "desert", "1f3dc"),
        Reaction("Travel & Places", "island", "1f3dd"),
        Reaction("Travel & Places", "national_park", "1f3de"),
        Reaction("Travel & Places", "stadium", "1f3df"),
        Reaction("Travel & Places", "classical_building", "1f3db"),
        Reaction("Travel & Places", "construction", "1f3d7"),
        Reaction("Travel & Places", "houses", "1f3d8"),
        Reaction("Travel & Places", "derelict_house", "1f3da"),
        Reaction("Travel & Places", "house", "1f3e0"),
        Reaction("Travel & Places", "suburb", "1f3e1"),
        Reaction("Travel & Places", "office", "1f3e2"),
        Reaction("Travel & Places", "japan_post", "1f3e3"),
        Reaction("Travel & Places", "post_office", "1f3e4"),
        Reaction("Travel & Places", "hospital", "1f3e5"),
        Reaction("Travel & Places", "bank", "1f3e6"),
        Reaction("Travel & Places", "hotel", "1f3e8"),
        Reaction("Travel & Places", "love_hotel", "1f3e9"),
        Reaction("Travel & Places", "convenience_store", "1f3ea"),
        Reaction("Travel & Places", "school", "1f3eb"),
        Reaction("Travel & Places", "department_store", "1f3ec"),
        Reaction("Travel & Places", "factory", "1f3ed"),
        Reaction("Travel & Places", "shiro", "1f3ef"),
        Reaction("Travel & Places", "castle", "1f3f0"),
        Reaction("Travel & Places", "wedding", "1f492"),
        Reaction("Travel & Places", "tower", "1f5fc"),
        Reaction("Travel & Places", "statue", "1f5fd"),
        Reaction("Travel & Places", "church", "26ea"),
        Reaction("Travel & Places", "mosque", "1f54c"),
        Reaction("Travel & Places", "synagogue", "1f54d"),
        Reaction("Travel & Places", "shinto_shrine", "26e9"),
        Reaction("Travel & Places", "kaaba", "1f54b"),
        Reaction("Travel & Places", "fountain", "26f2"),
        Reaction("Travel & Places", "tent", "26fa"),
        Reaction("Travel & Places", "foggy", "1f301"),
        Reaction("Travel & Places", "night", "1f303"),
        Reaction("Travel & Places", "city", "1f3d9"),
        Reaction("Travel & Places", "mountain_sunrise", "1f304"),
        Reaction("Travel & Places", "sunrise", "1f305"),
        Reaction("Travel & Places", "sunset", "1f306"),
        Reaction("Travel & Places", "city_sunrise", "1f307"),
        Reaction("Travel & Places", "bridge", "1f309"),
        Reaction("Travel & Places", "hot_springs", "2668"),
        Reaction("Travel & Places", "carousel", "1f3a0"),
        Reaction("Travel & Places", "ferris_wheel", "1f3a1"),
        Reaction("Travel & Places", "roller_coaster", "1f3a2"),
        Reaction("Travel & Places", "barber", "1f488"),
        Reaction("Travel & Places", "circus", "1f3aa"),
        Reaction("Travel & Places", "train", "1f682"),
        Reaction("Travel & Places", "railway_car", "1f683"),
        Reaction("Travel & Places", "high_speed_train", "1f684"),
        Reaction("Travel & Places", "bullet_train", "1f685"),
        Reaction("Travel & Places", "oncoming_train", "1f686"),
        Reaction("Travel & Places", "subway", "1f687"),
        Reaction("Travel & Places", "light_rail", "1f688"),
        Reaction("Travel & Places", "station", "1f689"),
        Reaction("Travel & Places", "oncoming_tram", "1f68a"),
        Reaction("Travel & Places", "monorail", "1f69d"),
        Reaction("Travel & Places", "mountain_railway", "1f69e"),
        Reaction("Travel & Places", "tram", "1f68b"),
        Reaction("Travel & Places", "bus", "1f68c"),
        Reaction("Travel & Places", "oncoming_bus", "1f68d"),
        Reaction("Travel & Places", "trolley", "1f68e"),
        Reaction("Travel & Places", "minibus", "1f690"),
        Reaction("Travel & Places", "ambulance", "1f691"),
        Reaction("Travel & Places", "fire_truck", "1f692"),
        Reaction("Travel & Places", "police_car", "1f693"),
        Reaction("Travel & Places", "oncoming_police_car", "1f694"),
        Reaction("Travel & Places", "taxi", "1f695"),
        Reaction("Travel & Places", "oncoming_taxi", "1f696"),
        Reaction("Travel & Places", "car", "1f697"),
        Reaction("Travel & Places", "oncoming_car", "1f698"),
        Reaction("Travel & Places", "recreational_vehicle", "1f699"),
        Reaction("Travel & Places", "moving_truck", "1f69a"),
        Reaction("Travel & Places", "truck", "1f69b"),
        Reaction("Travel & Places", "tractor", "1f69c"),
        Reaction("Travel & Places", "racecar", "1f3ce"),
        Reaction("Travel & Places", "motorcycle", "1f3cd"),
        Reaction("Travel & Places", "scooter", "1f6f5"),
        Reaction("Travel & Places", "bike", "1f6b2"),
        Reaction("Travel & Places", "kick_scooter", "1f6f4"),
        Reaction("Travel & Places", "bus_stop", "1f68f"),
        Reaction("Travel & Places", "road", "1f6e3"),
        Reaction("Travel & Places", "railway_track", "1f6e4"),
        Reaction("Travel & Places", "oil_drum", "1f6e2"),
        Reaction("Travel & Places", "fuel_pump", "26fd"),
        Reaction("Travel & Places", "siren", "1f6a8"),
        Reaction("Travel & Places", "horizontal_traffic_light", "1f6a5"),
        Reaction("Travel & Places", "traffic_light", "1f6a6"),
        Reaction("Travel & Places", "stop_sign", "1f6d1"),
        Reaction("Travel & Places", "work_in_progress", "1f6a7"),
        Reaction("Travel & Places", "anchor", "2693"),
        Reaction("Travel & Places", "boat", "26f5"),
        Reaction("Travel & Places", "canoe", "1f6f6"),
        Reaction("Travel & Places", "speedboat", "1f6a4"),
        Reaction("Travel & Places", "passenger_ship", "1f6f3"),
        Reaction("Travel & Places", "ferry", "26f4"),
        Reaction("Travel & Places", "motor_boat", "1f6e5"),
        Reaction("Travel & Places", "ship", "1f6a2"),
        Reaction("Travel & Places", "airplane", "2708"),
        Reaction("Travel & Places", "small_airplane", "1f6e9"),
        Reaction("Travel & Places", "take_off", "1f6eb"),
        Reaction("Travel & Places", "landing", "1f6ec"),
        Reaction("Travel & Places", "seat", "1f4ba"),
        Reaction("Travel & Places", "helicopter", "1f681"),
        Reaction("Travel & Places", "suspension_railway", "1f69f"),
        Reaction("Travel & Places", "gondola", "1f6a0"),
        Reaction("Travel & Places", "aerial_tramway", "1f6a1"),
        Reaction("Travel & Places", "satellite", "1f6f0"),
        Reaction("Travel & Places", "rocket", "1f680"),
        Reaction("Travel & Places", "bellhop_bell", "1f6ce"),
        Reaction("Travel & Places", "times_up", "231b"),
        Reaction("Travel & Places", "time_ticking", "23f3"),
        Reaction("Travel & Places", "watch", "231a"),
        Reaction("Travel & Places", "alarm_clock", "23f0"),
        Reaction("Travel & Places", "stopwatch", "23f1"),
        Reaction("Travel & Places", "timer", "23f2"),
        Reaction("Travel & Places", "mantelpiece_clock", "1f570"),
        Reaction("Travel & Places", "time", "1f557"),
        Reaction("Travel & Places", "new_moon", "1f311"),
        Reaction("Travel & Places", "waxing_moon", "1f314"),
        Reaction("Travel & Places", "full_moon", "1f315"),
        Reaction("Travel & Places", "moon", "1f319"),
        Reaction("Travel & Places", "new_moon_face", "1f31a"),
        Reaction("Travel & Places", "goodnight", "1f31b"),
        Reaction("Travel & Places", "temperature", "1f321"),
        Reaction("Travel & Places", "sunny", "2600"),
        Reaction("Travel & Places", "moon_face", "1f31d"),
        Reaction("Travel & Places", "sun_face", "1f31e"),
        Reaction("Travel & Places", "star", "2b50"),
        Reaction("Travel & Places", "glowing_star", "1f31f"),
        Reaction("Travel & Places", "shooting_star", "1f320"),
        Reaction("Travel & Places", "milky_way", "1f30c"),
        Reaction("Travel & Places", "cloud", "2601"),
        Reaction("Travel & Places", "partly_sunny", "26c5"),
        Reaction("Travel & Places", "thunderstorm", "26c8"),
        Reaction("Travel & Places", "mostly_sunny", "1f324"),
        Reaction("Travel & Places", "cloudy", "1f325"),
        Reaction("Travel & Places", "sunshowers", "1f326"),
        Reaction("Travel & Places", "rainy", "1f327"),
        Reaction("Travel & Places", "snowy", "1f328"),
        Reaction("Travel & Places", "lightning", "1f329"),
        Reaction("Travel & Places", "tornado", "1f32a"),
        Reaction("Travel & Places", "fog", "1f32b"),
        Reaction("Travel & Places", "windy", "1f32c"),
        Reaction("Travel & Places", "cyclone", "1f300"),
        Reaction("Travel & Places", "rainbow", "1f308"),
        Reaction("Travel & Places", "closed_umbrella", "1f302"),
        Reaction("Travel & Places", "umbrella", "2602"),
        Reaction("Travel & Places", "umbrella_with_rain", "2614"),
        Reaction("Travel & Places", "beach_umbrella", "26f1"),
        Reaction("Travel & Places", "high_voltage", "26a1"),
        Reaction("Travel & Places", "snowflake", "2744"),
        Reaction("Travel & Places", "snowman", "2603"),
        Reaction("Travel & Places", "frosty", "26c4"),
        Reaction("Travel & Places", "comet", "2604"),
        Reaction("Travel & Places", "fire", "1f525"),
        Reaction("Travel & Places", "drop", "1f4a7"),
        Reaction("Travel & Places", "ocean", "1f30a"),

// Objects
        Reaction("Objects", "glasses", "1f453"),
        Reaction("Objects", "dark_sunglasses", "1f576"),
        Reaction("Objects", "tie", "1f454"),
        Reaction("Objects", "shirt", "1f455"),
        Reaction("Objects", "jeans", "1f456"),
        Reaction("Objects", "dress", "1f457"),
        Reaction("Objects", "kimono", "1f458"),
        Reaction("Objects", "bikini", "1f459"),
        Reaction("Objects", "clothing", "1f45a"),
        Reaction("Objects", "purse", "1f45b"),
        Reaction("Objects", "handbag", "1f45c"),
        Reaction("Objects", "pouch", "1f45d"),
        Reaction("Objects", "shopping_bags", "1f6cd"),
        Reaction("Objects", "backpack", "1f392"),
        Reaction("Objects", "shoe", "1f45e"),
        Reaction("Objects", "athletic_shoe", "1f45f"),
        Reaction("Objects", "high_heels", "1f460"),
        Reaction("Objects", "sandal", "1f461"),
        Reaction("Objects", "boot", "1f462"),
        Reaction("Objects", "crown", "1f451"),
        Reaction("Objects", "hat", "1f452"),
        Reaction("Objects", "top_hat", "1f3a9"),
        Reaction("Objects", "graduate", "1f393"),
        Reaction("Objects", "helmet", "26d1"),
        Reaction("Objects", "prayer_beads", "1f4ff"),
        Reaction("Objects", "lipstick", "1f484"),
        Reaction("Objects", "ring", "1f48d"),
        Reaction("Objects", "gem", "1f48e"),
        Reaction("Objects", "mute", "1f507"),
        Reaction("Objects", "speaker", "1f508"),
        Reaction("Objects", "softer", "1f509"),
        Reaction("Objects", "louder", "1f50a"),
        Reaction("Objects", "loudspeaker", "1f4e2"),
        Reaction("Objects", "megaphone", "1f4e3"),
        Reaction("Objects", "horn", "1f4ef"),
        Reaction("Objects", "notifications", "1f514"),
        Reaction("Objects", "mute_notifications", "1f515"),
        Reaction("Objects", "musical_score", "1f3bc"),
        Reaction("Objects", "music", "1f3b5"),
        Reaction("Objects", "musical_notes", "1f3b6"),
        Reaction("Objects", "studio_microphone", "1f399"),
        Reaction("Objects", "volume", "1f39a"),
        Reaction("Objects", "control_knobs", "1f39b"),
        Reaction("Objects", "microphone", "1f3a4"),
        Reaction("Objects", "headphones", "1f3a7"),
        Reaction("Objects", "radio", "1f4fb"),
        Reaction("Objects", "saxophone", "1f3b7"),
        Reaction("Objects", "guitar", "1f3b8"),
        Reaction("Objects", "piano", "1f3b9"),
        Reaction("Objects", "trumpet", "1f3ba"),
        Reaction("Objects", "violin", "1f3bb"),
        Reaction("Objects", "drum", "1f941"),
        Reaction("Objects", "mobile_phone", "1f4f1"),
        Reaction("Objects", "calling", "1f4f2"),
        Reaction("Objects", "phone", "260e"),
        Reaction("Objects", "landline", "1f4de"),
        Reaction("Objects", "pager", "1f4df"),
        Reaction("Objects", "fax", "1f4e0"),
        Reaction("Objects", "battery", "1f50b"),
        Reaction("Objects", "electric_plug", "1f50c"),
        Reaction("Objects", "computer", "1f4bb"),
        Reaction("Objects", "desktop_computer", "1f5a5"),
        Reaction("Objects", "printer", "1f5a8"),
        Reaction("Objects", "keyboard", "2328"),
        Reaction("Objects", "computer_mouse", "1f5b1"),
        Reaction("Objects", "trackball", "1f5b2"),
        Reaction("Objects", "gold_record", "1f4bd"),
        Reaction("Objects", "floppy_disk", "1f4be"),
        Reaction("Objects", "cd", "1f4bf"),
        Reaction("Objects", "dvd", "1f4c0"),
        Reaction("Objects", "movie_camera", "1f3a5"),
        Reaction("Objects", "film", "1f39e"),
        Reaction("Objects", "projector", "1f4fd"),
        Reaction("Objects", "action", "1f3ac"),
        Reaction("Objects", "tv", "1f4fa"),
        Reaction("Objects", "camera", "1f4f7"),
        Reaction("Objects", "taking_a_picture", "1f4f8"),
        Reaction("Objects", "video_camera", "1f4f9"),
        Reaction("Objects", "vhs", "1f4fc"),
        Reaction("Objects", "search", "1f50d"),
        Reaction("Objects", "candle", "1f56f"),
        Reaction("Objects", "light_bulb", "1f4a1"),
        Reaction("Objects", "flashlight", "1f526"),
        Reaction("Objects", "lantern", "1f3ee"),
        Reaction("Objects", "decorative_notebook", "1f4d4"),
        Reaction("Objects", "red_book", "1f4d5"),
        Reaction("Objects", "book", "1f4d6"),
        Reaction("Objects", "green_book", "1f4d7"),
        Reaction("Objects", "blue_book", "1f4d8"),
        Reaction("Objects", "orange_book", "1f4d9"),
        Reaction("Objects", "books", "1f4da"),
        Reaction("Objects", "notebook", "1f4d3"),
        Reaction("Objects", "ledger", "1f4d2"),
        Reaction("Objects", "receipt", "1f4c3"),
        Reaction("Objects", "scroll", "1f4dc"),
        Reaction("Objects", "document", "1f4c4"),
        Reaction("Objects", "headlines", "1f4f0"),
        Reaction("Objects", "newspaper", "1f5de"),
        Reaction("Objects", "place_holder", "1f4d1"),
        Reaction("Objects", "bookmark", "1f516"),
        Reaction("Objects", "label", "1f3f7"),
        Reaction("Objects", "money", "1f4b0"),
        Reaction("Objects", "yen_banknotes", "1f4b4"),
        Reaction("Objects", "dollar_bills", "1f4b5"),
        Reaction("Objects", "euro_banknotes", "1f4b6"),
        Reaction("Objects", "pound_notes", "1f4b7"),
        Reaction("Objects", "losing_money", "1f4b8"),
        Reaction("Objects", "credit_card", "1f4b3"),
        Reaction("Objects", "stock_market", "1f4b9"),
        Reaction("Objects", "email", "2709"),
        Reaction("Objects", "e-mail", "1f4e7"),
        Reaction("Objects", "mail_received", "1f4e8"),
        Reaction("Objects", "mail_sent", "1f4e9"),
        Reaction("Objects", "outbox", "1f4e4"),
        Reaction("Objects", "inbox", "1f4e5"),
        Reaction("Objects", "package", "1f4e6"),
        Reaction("Objects", "mailbox", "1f4eb"),
        Reaction("Objects", "closed_mailbox", "1f4ea"),
        Reaction("Objects", "unread_mail", "1f4ec"),
        Reaction("Objects", "inbox_zero", "1f4ed"),
        Reaction("Objects", "mail_dropoff", "1f4ee"),
        Reaction("Objects", "ballot_box", "1f5f3"),
        Reaction("Objects", "pencil", "270f"),
        Reaction("Objects", "fountain_pen", "1f58b"),
        Reaction("Objects", "pen", "1f58a"),
        Reaction("Objects", "paintbrush", "1f58c"),
        Reaction("Objects", "crayon", "1f58d"),
        Reaction("Objects", "memo", "1f4dd"),
        Reaction("Objects", "briefcase", "1f4bc"),
        Reaction("Objects", "organize", "1f4c1"),
        Reaction("Objects", "folder", "1f4c2"),
        Reaction("Objects", "sort", "1f5c2"),
        Reaction("Objects", "calendar", "1f4c5"),
        Reaction("Objects", "date", "1f4c6"),
        Reaction("Objects", "spiral_notepad", "1f5d2"),
        Reaction("Objects", "rolodex", "1f4c7"),
        Reaction("Objects", "chart", "1f4c8"),
        Reaction("Objects", "downwards_trend", "1f4c9"),
        Reaction("Objects", "bar_chart", "1f4ca"),
        Reaction("Objects", "clipboard", "1f4cb"),
        Reaction("Objects", "push_pin", "1f4cc"),
        Reaction("Objects", "pin", "1f4cd"),
        Reaction("Objects", "paperclip", "1f4ce"),
        Reaction("Objects", "office_supplies", "1f587"),
        Reaction("Objects", "ruler", "1f4cf"),
        Reaction("Objects", "carpenter_square", "1f4d0"),
        Reaction("Objects", "scissors", "2702"),
        Reaction("Objects", "archive", "1f5c3"),
        Reaction("Objects", "file_cabinet", "1f5c4"),
        Reaction("Objects", "wastebasket", "1f5d1"),
        Reaction("Objects", "locked", "1f512"),
        Reaction("Objects", "unlocked", "1f513"),
        Reaction("Objects", "privacy", "1f50f"),
        Reaction("Objects", "secure", "1f510"),
        Reaction("Objects", "key", "1f511"),
        Reaction("Objects", "secret", "1f5dd"),
        Reaction("Objects", "hammer", "1f528"),
        Reaction("Objects", "mine", "26cf"),
        Reaction("Objects", "at_work", "2692"),
        Reaction("Objects", "working_on_it", "1f6e0"),
        Reaction("Objects", "dagger", "1f5e1"),
        Reaction("Objects", "duel", "2694"),
        Reaction("Objects", "gun", "1f52b"),
        Reaction("Objects", "bow_and_arrow", "1f3f9"),
        Reaction("Objects", "shield", "1f6e1"),
        Reaction("Objects", "fixing", "1f527"),
        Reaction("Objects", "nut_and_bolt", "1f529"),
        Reaction("Objects", "gear", "2699"),
        Reaction("Objects", "compression", "1f5dc"),
        Reaction("Objects", "justice", "2696"),
        Reaction("Objects", "link", "1f517"),
        Reaction("Objects", "chains", "26d3"),
        Reaction("Objects", "alchemy", "2697"),
        Reaction("Objects", "science", "1f52c"),
        Reaction("Objects", "telescope", "1f52d"),
        Reaction("Objects", "satellite_antenna", "1f4e1"),
        Reaction("Objects", "injection", "1f489"),
        Reaction("Objects", "medicine", "1f48a"),
        Reaction("Objects", "door", "1f6aa"),
        Reaction("Objects", "bed", "1f6cf"),
        Reaction("Objects", "living_room", "1f6cb"),
        Reaction("Objects", "toilet", "1f6bd"),
        Reaction("Objects", "shower", "1f6bf"),
        Reaction("Objects", "bathtub", "1f6c1"),
        Reaction("Objects", "shopping_cart", "1f6d2"),
        Reaction("Objects", "smoking", "1f6ac"),
        Reaction("Objects", "coffin", "26b0"),
        Reaction("Objects", "funeral_urn", "26b1"),
        Reaction("Objects", "rock_carving", "1f5ff"),

// Symbols
        Reaction("Symbols", "atm", "1f3e7"),
        Reaction("Symbols", "put_litter_in_its_place", "1f6ae"),
        Reaction("Symbols", "potable_water", "1f6b0"),
        Reaction("Symbols", "accessible", "267f"),
        Reaction("Symbols", "mens", "1f6b9"),
        Reaction("Symbols", "womens", "1f6ba"),
        Reaction("Symbols", "restroom", "1f6bb"),
        Reaction("Symbols", "baby_change_station", "1f6bc"),
        Reaction("Symbols", "wc", "1f6be"),
        Reaction("Symbols", "passport_control", "1f6c2"),
        Reaction("Symbols", "customs", "1f6c3"),
        Reaction("Symbols", "baggage_claim", "1f6c4"),
        Reaction("Symbols", "locker", "1f6c5"),
        Reaction("Symbols", "warning", "26a0"),
        Reaction("Symbols", "children_crossing", "1f6b8"),
        Reaction("Symbols", "no_entry", "26d4"),
        Reaction("Symbols", "prohibited", "1f6ab"),
        Reaction("Symbols", "no_bicycles", "1f6b3"),
        Reaction("Symbols", "no_smoking", "1f6ad"),
        Reaction("Symbols", "do_not_litter", "1f6af"),
        Reaction("Symbols", "non-potable_water", "1f6b1"),
        Reaction("Symbols", "no_pedestrians", "1f6b7"),
        Reaction("Symbols", "no_phones", "1f4f5"),
        Reaction("Symbols", "underage", "1f51e"),
        Reaction("Symbols", "radioactive", "2622"),
        Reaction("Symbols", "biohazard", "2623"),
        Reaction("Symbols", "up", "2b06"),
        Reaction("Symbols", "upper_right", "2197"),
        Reaction("Symbols", "right", "27a1"),
        Reaction("Symbols", "lower_right", "2198"),
        Reaction("Symbols", "down", "2b07"),
        Reaction("Symbols", "lower_left", "2199"),
        Reaction("Symbols", "left", "2b05"),
        Reaction("Symbols", "upper_left", "2196"),
        Reaction("Symbols", "up_down", "2195"),
        Reaction("Symbols", "left_right", "2194"),
        Reaction("Symbols", "reply", "21a9"),
        Reaction("Symbols", "forward", "21aa"),
        Reaction("Symbols", "heading_up", "2934"),
        Reaction("Symbols", "heading_down", "2935"),
        Reaction("Symbols", "clockwise", "1f503"),
        Reaction("Symbols", "counterclockwise", "1f504"),
        Reaction("Symbols", "back", "1f519"),
        Reaction("Symbols", "end", "1f51a"),
        Reaction("Symbols", "on", "1f51b"),
        Reaction("Symbols", "soon", "1f51c"),
        Reaction("Symbols", "top", "1f51d"),
        Reaction("Symbols", "place_of_worship", "1f6d0"),
        Reaction("Symbols", "atom", "269b"),
        Reaction("Symbols", "om", "1f549"),
        Reaction("Symbols", "star_of_david", "2721"),
        Reaction("Symbols", "wheel_of_dharma", "2638"),
        Reaction("Symbols", "yin_yang", "262f"),
        Reaction("Symbols", "cross", "271d"),
        Reaction("Symbols", "orthodox_cross", "2626"),
        Reaction("Symbols", "star_and_crescent", "262a"),
        Reaction("Symbols", "peace", "262e"),
        Reaction("Symbols", "menorah", "1f54e"),
        Reaction("Symbols", "aries", "2648"),
        Reaction("Symbols", "taurus", "2649"),
        Reaction("Symbols", "gemini", "264a"),
        Reaction("Symbols", "cancer", "264b"),
        Reaction("Symbols", "leo", "264c"),
        Reaction("Symbols", "virgo", "264d"),
        Reaction("Symbols", "libra", "264e"),
        Reaction("Symbols", "scorpius", "264f"),
        Reaction("Symbols", "sagittarius", "2650"),
        Reaction("Symbols", "capricorn", "2651"),
        Reaction("Symbols", "aquarius", "2652"),
        Reaction("Symbols", "pisces", "2653"),
        Reaction("Symbols", "ophiuchus", "26ce"),
        Reaction("Symbols", "shuffle", "1f500"),
        Reaction("Symbols", "repeat", "1f501"),
        Reaction("Symbols", "repeat_one", "1f502"),
        Reaction("Symbols", "play", "25b6"),
        Reaction("Symbols", "fast_forward", "23e9"),
        Reaction("Symbols", "next_track", "23ed"),
        Reaction("Symbols", "play_pause", "23ef"),
        Reaction("Symbols", "play_reverse", "25c0"),
        Reaction("Symbols", "rewind", "23ea"),
        Reaction("Symbols", "previous_track", "23ee"),
        Reaction("Symbols", "upvote", "1f53c"),
        Reaction("Symbols", "double_up", "23eb"),
        Reaction("Symbols", "downvote", "1f53d"),
        Reaction("Symbols", "double_down", "23ec"),
        Reaction("Symbols", "pause", "23f8"),
        Reaction("Symbols", "stop_button", "23f9"),
        Reaction("Symbols", "record", "23fa"),
        Reaction("Symbols", "cinema", "1f3a6"),
        Reaction("Symbols", "low_brightness", "1f505"),
        Reaction("Symbols", "brightness", "1f506"),
        Reaction("Symbols", "cell_reception", "1f4f6"),
        Reaction("Symbols", "vibration_mode", "1f4f3"),
        Reaction("Symbols", "phone_off", "1f4f4"),
        Reaction("Symbols", "multiplication", "2716"),
        Reaction("Symbols", "plus", "2795"),
        Reaction("Symbols", "minus", "2796"),
        Reaction("Symbols", "division", "2797"),
        Reaction("Symbols", "bangbang", "203c"),
        Reaction("Symbols", "interrobang", "2049"),
        Reaction("Symbols", "question", "2753"),
        Reaction("Symbols", "grey_question", "2754"),
        Reaction("Symbols", "grey_exclamation", "2755"),
        Reaction("Symbols", "exclamation", "2757"),
        Reaction("Symbols", "wavy_dash", "3030"),
        Reaction("Symbols", "exchange", "1f4b1"),
        Reaction("Symbols", "dollars", "1f4b2"),
        Reaction("Symbols", "recycle", "267b"),
        Reaction("Symbols", "fleur_de_lis", "269c"),
        Reaction("Symbols", "trident", "1f531"),
        Reaction("Symbols", "name_badge", "1f4db"),
        Reaction("Symbols", "beginner", "1f530"),
        Reaction("Symbols", "circle", "2b55"),
        Reaction("Symbols", "check", "2705"),
        Reaction("Symbols", "checkbox", "2611"),
        Reaction("Symbols", "check_mark", "2714"),
        Reaction("Symbols", "cross_mark", "274c"),
        Reaction("Symbols", "x", "274e"),
        Reaction("Symbols", "loop", "27b0"),
        Reaction("Symbols", "double_loop", "27bf"),
        Reaction("Symbols", "part_alternation", "303d"),
        Reaction("Symbols", "eight_spoked_asterisk", "2733"),
        Reaction("Symbols", "eight_pointed_star", "2734"),
        Reaction("Symbols", "sparkle", "2747"),
        Reaction("Symbols", "tm", "2122"),
        Reaction("Symbols", "hash", "0023"),
        Reaction("Symbols", "asterisk", "002a"),
        Reaction("Symbols", "zero", "0030"),
        Reaction("Symbols", "one", "0031"),
        Reaction("Symbols", "two", "0032"),
        Reaction("Symbols", "three", "0033"),
        Reaction("Symbols", "four", "0034"),
        Reaction("Symbols", "five", "0035"),
        Reaction("Symbols", "six", "0036"),
        Reaction("Symbols", "seven", "0037"),
        Reaction("Symbols", "eight", "0038"),
        Reaction("Symbols", "nine", "0039"),
        Reaction("Symbols", "ten", "1f51f"),
        Reaction("Symbols", "capital_abcd", "1f520"),
        Reaction("Symbols", "abcd", "1f521"),
        Reaction("Symbols", "1234", "1f522"),
        Reaction("Symbols", "symbols", "1f523"),
        Reaction("Symbols", "abc", "1f524"),
        Reaction("Symbols", "a", "1f170"),
        Reaction("Symbols", "ab", "1f18e"),
        Reaction("Symbols", "b", "1f171"),
        Reaction("Symbols", "cl", "1f191"),
        Reaction("Symbols", "cool", "1f192"),
        Reaction("Symbols", "free", "1f193"),
        Reaction("Symbols", "info", "2139"),
        Reaction("Symbols", "id", "1f194"),
        Reaction("Symbols", "metro", "24c2"),
        Reaction("Symbols", "new", "1f195"),
        Reaction("Symbols", "ng", "1f196"),
        Reaction("Symbols", "o", "1f17e"),
        Reaction("Symbols", "squared_ok", "1f197"),
        Reaction("Symbols", "parking", "1f17f"),
        Reaction("Symbols", "sos", "1f198"),
        Reaction("Symbols", "squared_up", "1f199"),
        Reaction("Symbols", "vs", "1f19a"),
        Reaction("Symbols", "red_circle", "1f534"),
        Reaction("Symbols", "blue_circle", "1f535"),
        Reaction("Symbols", "black_circle", "26ab"),
        Reaction("Symbols", "white_circle", "26aa"),
        Reaction("Symbols", "black_large_square", "2b1b"),
        Reaction("Symbols", "white_large_square", "2b1c"),
        Reaction("Symbols", "black_medium_square", "25fc"),
        Reaction("Symbols", "white_medium_square", "25fb"),
        Reaction("Symbols", "black_medium_small_square", "25fe"),
        Reaction("Symbols", "white_medium_small_square", "25fd"),
        Reaction("Symbols", "black_small_square", "25aa"),
        Reaction("Symbols", "white_small_square", "25ab"),
        Reaction("Symbols", "large_orange_diamond", "1f536"),
        Reaction("Symbols", "large_blue_diamond", "1f537"),
        Reaction("Symbols", "small_orange_diamond", "1f538"),
        Reaction("Symbols", "small_blue_diamond", "1f539"),
        Reaction("Symbols", "red_triangle_up", "1f53a"),
        Reaction("Symbols", "red_triangle_down", "1f53b"),
        Reaction("Symbols", "cute", "1f4a0"),
        Reaction("Symbols", "radio_button", "1f518"),
        Reaction("Symbols", "black_and_white_square", "1f533"),
        Reaction("Symbols", "white_and_black_square", "1f532"),
        // Flags
        Reaction("Flags", "checkered_flag", "1f3c1"),
        Reaction("Flags", "triangular_flag", "1f6a9"),
        Reaction("Flags", "crossed_flags", "1f38c"),
        Reaction("Flags", "black_flag", "1f3f4"),
        Reaction("Flags", "white_flag", "1f3f3")
    )
}
